### ISSUE TITLE
What's the Python version please?

### ISSUE THREAD

**Issue by AmoseCP** [lds133/weather_landscape#3]
I installed pillow-10.4.0 with Python 3.12.3, not work, "ModuleNotFoundError: No module named 'PIL'"

**Comment by lds133** [comment]
As mentioned in the readme, the scripts have been tested with Python 3.9. I think any Python 3 version with the pillow library installed should work.

**Comment by lds133** [comment]
Type "pip install pillow" to install the library manually.
