### ISSUE TITLE
ValueError: need more than 1 values to unpack

### ISSUE THREAD

**Issue by fishfree** [lds133/weather_landscape#7]
I strictly followed the READMEs. However, the waveshare screen did not light up and erorr occured as below:
![image](https://github.com/user-attachments/assets/eed96ff8-6348-4160-8146-1b09428a73b0)
I connected the ESP32 board and Waveshare screen strictly as your photos in the [README](https://github.com/lds133/weather_landscape/blob/main/esp32/README.md).

I notice [`PIN_DIN = 19`](https://github.com/lds133/weather_landscape/blob/19f98e060ff974bc9f1c4d8eee0e29ded8fd21a6/esp32/board/appconfig.py#L9), however, the D19 pin on the ESP32 board is not wired as your photos.
What's wrong with mine?  I'm a total novice to this scope. FYI: here is [the official specification book](https://www.waveshare.net/w/upload/b/bb/2.9inch-e-paper-b-specification.pdf) of Waveshare E-Ink.

**Comment by LLLLimbo** [comment]
I’m facing the same issue, not sure what’s causing it either.

**Comment by lds133** [comment]
Please try to check if the image is accessible. Connect to the same wifi from your phone and enter the url to the test.bmp. You should see the image in portrait orientation. The expected size of the image is 4798 bytes.

Sorry, there is a confusion about the pin names. Pin 23 is used as MOSI, pin 19 (MISO) is unused.

**Comment by fishfree** [comment]
@lds133 Thank you very much! I updated the 2 files, re-flash MicroPython into my ESP32 board, re-upload all the scripts with Thonny. However, the errors still occured the same.

**Comment by lds133** [comment]
The most recent update was a cosmetic and is not intended to fix the problem.
If the image is accessible through the local wifi, it is the expected size, and the board has successfully connected to the wifi  more investigation is needed for the ["get" function](https://github.com/lds133/weather_landscape/blob/3ac39be54b2e6e2390ee6aa494c87f2bf593a5c8/esp32/board/wifi.py#L49) of the Micro Python requests library. 
I would start by checking if it works in general, checking if it is possible to "get" something from a well-known url.

**Comment by fishfree** [comment]
@lds133 Thank you! I checked in the Web admin-UI of my WiFi that my ESP32 had connected my WiFi.

**Comment by shadowwider** [comment]
I encounter the same issue, quite strange errors. The image is accessible, and the development board's network is normal. However, when I access a regular website, there are no errors, but accessing the image seems to cause them.

I also found that getting other images as long as they are not too large is normal. However, reading the BMP image generated on my server side results in an error.

**Comment by shadowwider** [comment]
> @shadowwider Did your Waveshare screen light up after running with the error? Mine is not.

I haven't received my led screen yet. I'm just running a test directly on the development board to see if it's working properly. But I've noticed that the same problem occurs when requesting images.

**Comment by lds133** [comment]
Unfortunately, I can't reproduce the problem you're describing. I believe the python's behavior can vary significantly depending on the hardware. My best guess is that there isn't enough memory to read and process the file in one go on your hardware. In this case, reading the file in chunks may help.

To test if the Eink display works, please uncomment the next 2 lines:
https://github.com/lds133/weather_landscape/blob/3ac39be54b2e6e2390ee6aa494c87f2bf593a5c8/esp32/board/main.py#L40
This will cause the startup message to be displayed as shown in the image:
https://github.com/lds133/weather_landscape/blob/main/esp32/pic/20240731_121744_cr.png

**Comment by shadowwider** [comment]
> Unfortunately, I can't reproduce the problem you're describing. I believe the python's behavior can vary significantly depending on the hardware. My best guess is that there isn't enough memory to read and process the file in one go on your hardware. In this case, reading the file in chunks may help.
> 
> To test if the Eink display works, please uncomment the next 2 lines:
> 
> https://github.com/lds133/weather_landscape/blob/3ac39be54b2e6e2390ee6aa494c87f2bf593a5c8/esp32/board/main.py#L40
> 
> 
> This will cause the startup message to be displayed as shown in the image:
> https://github.com/lds133/weather_landscape/blob/main/esp32/pic/20240731_121744_cr.png

Thanks your reply. It seems that there is a problem with the httpd module in certain situations, causing issues with the board's requests. My current approach is to use nginx to display images and run run_test.py to periodically generate images placed in the website's static files folder, which will not result in errors.

**Comment by echokk11** [comment]
same issue
![Xnip2024-11-04_15-43-19](https://github.com/user-attachments/assets/e286541e-8410-4d71-86f5-31fd8eed2ccc)
