### ISSUE TITLE
Compatibility issue with v2 e-Paper display: Image misalignment

### ISSUE THREAD

**Issue by shadowwider** [lds133/weather_landscape#8]
Hello,

I'm really interested in this cool little project, and I'm currently working on it as a birthday gift for my son. However, I've encountered an issue. The original v1 version of the e-Paper display is no longer available, and I could only get the v2 version. Unfortunately, the code doesn't seem to be compatible with this version.

I've done my best to find some resources and got the display to show something, but the images are misaligned and appear offset. Since I'm not very experienced with hardware development, I'm finding it quite confusing and am unsure how to properly control the display behavior.

I've attached a "jpg" file with my modified code. Would it be possible for you to help me correct it so that it works properly with the v2 version? I'd really appreciate any assistance you can provide. Thanks in advance!
[2.9inch-e-paper-v2-specification (1).pdf](https://github.com/user-attachments/files/17468766/2.9inch-e-paper-v2-specification.1.pdf)
![epaper2in9](https://github.com/user-attachments/assets/84422961-3819-4d9f-b1fb-56db509a7f7d)

**Comment by shadowwider** [comment]
You can find Python sample codes for the Raspberry Pi 2in9v2 provided by [here](https://www.waveshare.net/w/upload/7/71/E-Paper_code.zip)

**Comment by lds133** [comment]
Hello.
Unfortunately, I’m unable to dedicate more time to this project at the moment, and I can't implement support for a new hardware version without having the hardware myself. I recommend visiting the repository where I found the current code. Although it's quite old, there may be updates or helpful hints in the discussions. 
https://github.com/lds133/weather_landscape/blob/3ac39be54b2e6e2390ee6aa494c87f2bf593a5c8/esp32/board/epaper2in9.py#L3
Alternatively, you could try porting the code from the Waveshare examples. It might make more sense to start with the C code, as it could be easier to port to MicroPython than Python.

**Comment by shadowwider** [comment]
I got V2 e-Paper compatibility adjustments right, now it's usable. If anyone else has encountered a similar problem, they can refer to this [fork](https://github.com/shadowwider/weather_landscape). Since no modifications for compatibility were made, it wasn't submitted here; I just want it to work with V2 for myself.

The low-level driver e-Paper code is based on the official project. [here] (https://www.waveshare.net/wiki/Pico-ePaper-2.9)
